# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Seed dispersal across a spatial grid
#'
#' @param S A matrix of seed counts across a spatial grid.
#' @param N A neighbor matrix, e.g. produced by \code{neighborhood()}.
#' @param rand Randomize dispersal? (Boolean, default = TRUE).
#' @param seed Integer to seed random number generator.
#' @return A matrix of post-dispersal seed counts of the same dimension as \code{S}.
#' @export
disperse <- function(S, N, rand = TRUE, seed = 1L) {
    .Call(`_stranger_disperse`, S, N, rand, seed)
}

#' Perform a randomized stage-based demographic transition
#'
#' @param N A 3-D array of population numbers for each life stage, over a spatial grid (x, y, class).
#' @param E A 4-D array of environmental data (x, y, time, variable).
#' @param alpha A matrix of transition intercepts (from, to).
#' @param beta A 3-D array of density dependence effects (from, to, modifier).
#' @param gamma A 3-D array of environmental effects (from, to, variable).
#' @param fecundity Multiplier applied to first life stage after transition.
#' @param rand Randomize transitions instead of using matrix multiplication? (Boolean, default = TRUE).
#' @param seed Integer to seed random number generator.
#' @return A 3-D array of population numbers for each life stage.
#' @export
transition <- function(N, E, alpha, beta, gamma, fecundity = 1, rand = TRUE, seed = 1L) {
    .Call(`_stranger_transition`, N, E, alpha, beta, gamma, fecundity, rand, seed)
}

